apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - hello
  selector:
    matchLabels:
      app: hello-world
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
